version: '3'

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local


services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      frontproxy_fnet:
        ipv4_address: 172.18.18.70
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "4096m"

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    ports:
      - 9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - /etc/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      frontproxy_fnet:
        ipv4_address: 172.18.18.71
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "4096m"


  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    logging:
      driver: "json-file"
      options:
        max-size: "4096m"
    networks:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "4096m"
    networks:
      - backend


networks:
  frontproxy_fnet:
     external: true
  backend:
    name: monitoring_backend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"