version: '3'
services:
  angularshowcase:
    container_name: angularshowcase
    build: .
    restart: unless-stopped
    networks:
      frontproxy_fnet:
        ipv4_address: 172.18.18.90
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"



networks:
  frontproxy_fnet:
    external: true
  backend:
    name: showcase_backend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"