version: "3"
services:
  fastapi:
    environment:
      ROOTPATH: "/hello_api"
    build:
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: unless-stopped
    container_name: hello_api
    networks:
      frontproxy_fnet:
        ipv4_address: 172.18.18.40
    volumes:
      - ./app:/code/app

networks:
  frontproxy_fnet:
     external: true
  #Hier ggf. das Datenbanknetzwerk!