version: '3'
services:
  aigruppe_mysql:
    image: mysql:8.0.30
    volumes:
      - ./aigruppe-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    user: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    container_name: aigruppe-mysql
    networks:
      - gruppeai_intern

  wordpress:
    image: wordpress:6.4.1-php8.1-apache
    volumes:
      - ./aigruppe-html:/var/www/html
      - ./config/gruppe.ai.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - aigruppe_mysql
    environment:
      WORDPRESS_DB_HOST: aigruppe_mysql
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    links:
      - aigruppe_mysql
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    cap_add:
      - CAP_NET_BIND_SERVICE
    user: "www-data"
    container_name: aigruppe-wordpress
    networks:
      frontproxy_fnet:
        ipv4_address: 172.18.18.21
      gruppeai_intern:

networks:
  frontproxy_fnet:
     external: true
  gruppeai_intern:
    name: aigruppe_backend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
