version: "3.2"
services:

  outline:
    image: outlinewiki/outline:0.73.1
    container_name: Outline
#    env_file: ./.env
    ports:
      - 3000
    volumes:
      - /opt/outline.gruppe.ai/storage-data:/var/lib/outline/data
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@postgres:5432/outline
      - REDIS_URL=redis://redis:6379
      - URL=https://outline.gruppe.ai
      - PORT=3000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_UPLOAD_BUCKET_URL=https://minio.gruppe.ai
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - OIDC_CLIENT_ID=outline
      - OIDC_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - OIDC_AUTH_URI=https://keycloak.gruppe.ai/auth/realms/AI-Gruppe/protocol/openid-connect/auth
      - OIDC_TOKEN_URI=https://keycloak.gruppe.ai/auth/realms/AI-Gruppe/protocol/openid-connect/token
      - OIDC_USERINFO_URI=https://keycloak.gruppe.ai/auth/realms/AI-Gruppe/protocol/openid-connect/userinfo
      - OIDC_USERNAME_CLAIM=email
      - OIDC_DISPLAY_NAME=Keycloak
      - OIDC_SCOPES=email
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
    links:
      - postgres
    networks:
      outline:
        #       ipv4_address: 172.22.22.10
      frontproxy_fnet:
        ipv4_address: 172.18.18.61

  redis:
    image: redis:7.2.3
    container_name: Outline-Redis
#    env_file: ./.env
    ports:
      - 6379
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - outline
        #        ipv4_address: 172.22.22.11

  postgres:
    image: postgres:15.5-alpine3.18
    container_name: postgres
#    env_file: ./.env
    ports:
      - 5432
    volumes:
      - /opt/outline.gruppe.ai/database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - PGUSER=outline
      - POSTGRES_USER=outline
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=outline
    restart: unless-stopped
    networks:
      - outline

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: Outline-minio
    volumes:
      - /home/philipp/outline/minio/data:/data:Z
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=https://minio-admin.gruppe.ai
    # ports:
      # - 9000:9000
      # - 9001:9001
    networks:
      frontproxy_fnet:
        ipv4_address: 172.18.18.62
      outline:
    command: "server /data --console-address :9001"

networks:
  frontproxy_fnet:
    external: true
  outline:
