version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      VIRTUAL_HOST: p-heimdall.gruppe.ai
    volumes:
      - ./heimdall/config:/config
    restart: unless-stopped
    networks:
      frontproxy_fnet:
        ipv4_address: 172.18.18.60
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"

networks:
  frontproxy_fnet:
     external: true
  backend:
    name: heimdall_backend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"